use banco;


CREATE TABLE IF NOT EXISTS usuarios(
    usuarios INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(45) NOT NULL,
    password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS items(
    items INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    cost VARCHAR(200) NOT NULL
);